views/main_views.py
from flask import Blueprint, render_template, request, redirect, url_for
import uuid
from datetime import datetime 

from models import Firewall, TicketModel, AccessModel, ErrorModel
from forms import RuleUpdateForm, TicketUpdateForm
from configs import FIREWALL_COLUMN_HEADER, TICKET_COLUMN_HEADER, ACCESS_COLUMN_HEADER, ERROR_COLUMN_HEADER, ANALYZE_SITE, FIREWALL_SITE

# blueprint
bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/', methods=['GET', 'POST'])
def index():
    return redirect(url_for('main.ticket'))

@bp.route('/firewall', methods=['GET', 'POST'])
def firewall():
    page = request.args.get('page', default=1)

    analyze_site = ANALYZE_SITE
    management = Firewall()
    form = RuleUpdateForm()
    nonce = uuid.uuid4().hex
    if request.method == 'POST' and form.validate_on_submit():
        request_data = {'ip': form.ip.data, 'ip_class':form.ip_class.data, 'protocol': form.protocol.data, 'port': form.port.data, 'block': form.block.data, 'timestamp': datetime.now()}
        management.post(request_data=request_data)

    column_header = FIREWALL_COLUMN_HEADER
    update_title = 'Firewall'

    paging, data_list = management.get(page=page)
    return render_template('pages/firewall.html', **locals())

@bp.route('/ticket', methods=['GET', 'POST'])
def ticket():
    page = request.args.get('page', default=1)

    analyze_site = ANALYZE_SITE
    management = TicketModel()
    form = TicketUpdateForm()
    nonce = uuid.uuid4().hex
    if request.method == 'POST':
        request_data = {'_id': form.id.data, 'fix':form.fix.data, 'fix_timestamp': datetime.now()}
        management.post(request_data=request_data)

    column_header = TICKET_COLUMN_HEADER
    update_title = 'Ticket'

    paging, data_list = management.get(page=page)
    return render_template('pages/ticket.html', **locals())

@bp.route('/ticket/<ticket>', methods=['GET'])
def history(ticket):
    page = request.args.get('page', default=1)

    analyze_site = ANALYZE_SITE
    management = AccessModel()
    column_header = ACCESS_COLUMN_HEADER
    update_title = 'Access'

    paging, data_list = management.get_by_ticket(ticket, page=page)
    return render_template('pages/access.html', **locals())

@bp.route('/access_log', methods=['GET'])
def access():
    page = request.args.get('page', default=1)

    analyze_site = ANALYZE_SITE
    management = AccessModel()
    column_header = ACCESS_COLUMN_HEADER
    paging, data_list = management.get(page=page)
    return render_template('pages/access.html', **locals())

@bp.route('/access_log/site/<site>', methods=['GET'])
def access_by_site(site):
    page = request.args.get('page', default=1)

    analyze_site = ANALYZE_SITE
    management = AccessModel()
    column_header = ACCESS_COLUMN_HEADER
    paging, data_list = management.get_by_site(site, page=page)
    return render_template('pages/access.html', **locals())

@bp.route('/access_log/status/<status>', methods=['GET'])
def access_by_status(status):
    page = request.args.get('page', default=1)

    analyze_site = ANALYZE_SITE
    management = AccessModel()
    column_header = ACCESS_COLUMN_HEADER
    paging, data_list = management.get_by_status(status, page=page)
    return render_template('pages/access.html', **locals())

@bp.route('/error_log', methods=['GET'])
def error():
    page = request.args.get('page', default=1)

    analyze_site = ANALYZE_SITE
    management = ErrorModel()
    column_header = ERROR_COLUMN_HEADER
    paging, data_list = management.get(page=page)
    return render_template('pages/access.html', **locals())

@bp.route('/load_chart', methods=['GET'])
def load():
    url = FIREWALL_SITE + 'api/loads'
    nonce = uuid.uuid4().hex
    return render_template('pages/load.html', **locals())

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Log Management</title>
    <meta charset="utf-8">
    <meta http-equiv="Content-Security-Policy" content="script-src 'self' 'nonce-{{ nonce }}' code.jquery.com cdn.jsdelivr.net;">
    <!-- Bootstrap CSS -->
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" 
        crossorigin="anonymous"
    >
    <!-- JavaScript Bundle with Popper -->
    <script 
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" 
        crossorigin="anonymous"
    >
    </script>
    <script
        src="https://code.jquery.com/jquery-3.6.1.min.js"
        integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
        crossorigin="anonymous"
    >
    </script>
</head>
<body>
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html

templates/chart.html
<div>
    <canvas id="myChart"></canvas>
</div>
  
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script nonce="{{ nonce }}">
    const ctx = document.getElementById('myChart')

    $(document).ready(function(){
        $.ajax({
            type: 'get',
            url : '{{ url }}',
            dataType: 'json', 
            success: function(result){
                const data_dict = result
                const data = {
                    labels: data_dict.timestamp,
                    datasets: [{
                        label: 'CPU Usage',
                        data: data_dict.cpu,
                        borderColor: 'rgb(255, 99, 132)',
                        backgroundColor: 'rgb(255, 99, 132, 0.5)',
                        yAxisID: 'y',
                    },
                    {
                        label: 'MEM Usage',
                        data: data_dict.mem,
                        borderColor: 'rgb(54, 162, 235)',
                        backgroundColor: 'rgb(54, 162, 235, 0.5)',
                        yAxisID: 'y1',
                    }]
                }
                const config = {
                    type: 'line',
                    data: data,
                    options: {
                        responsive: true,
                        interaction: {
                            mode: 'index',
                            intersect: false,
                        },
                        stacked: false,
                        plugins: {
                            title: {
                                display: false,
                                text: 'Chart.js Line Chart - Multi Axis'
                            }
                        },
                        scales: {
                            y: {
                                type: 'linear',
                                display: true,
                                position: 'left',
                                min: 0,
                                max: 100
                            },
                            y1: {
                                type: 'linear',
                                display: true,
                                position: 'right',
                                // grid line settings
                                grid: {
                                    drawOnChartArea: false, // only want the grid lines for one axis to show up
                                },
                                min: 0,
                                max: 100,
                            },
                        },
                        layout: {padding: 30}
                    },
                }
                new Chart(ctx, config)
            },
            error:function(err){  
                console.log(err)
            }
        })
    })
</script>

templates/event_handler.html
<script nonce="{{ nonce }}">
    {% for i, data in enumerate(data_list) %}
    $("#td{{ loop.index0 }}").click(function() {
        handleClick({{ data|tojson }}, {{ i }});
    });
    {% endfor %}
</script>

templates/form_errors.html
<!-- ------------------------------ [edit] -------------------------------- -->
<!-- 필드오류 -->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}
<!-- ---------------------------------------------------------------------- -->

templates/modal.html
<!-- Modal -->
<div class="modal fade" id="modalForm" tabindex="-1" aria-labelledby="modalFormLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold" id="modalFormLabel">{{ update_title }}</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" class="fw-form" id="fw-form">
                    {{ form.csrf_token }}
                    {% include 'form_errors.html' %}
                    <div class="form-group my-3">
                        <input type="hidden" class="form-control" name="no" id="no" value="{{ '' }}">
                    </div>
                    {% for field in form %}
                    <div class="form-group my-3">
                        {% if field.id not in ['csrf_token', 'id'] %}
                        {{ field.label }}
                        {% endif %}
                        {% if field.id not in ['csrf_token', 'id'] %}
                        {{ field(class_='form-control') }}
                        {% elif field.id in ['id'] %}
                        {{ field(type='hidden', class_='form-control') }}
                        {% endif %}
                    </div>
                    {% endfor %}    
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="btn-save">Save changes</button>
                <button type="button" class="btn btn-primary" id="btn-delete">Delete</button>
            </div>
        </div>
    </div>
</div>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">LOG MANAGEMENT</a>
        <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a {% if request.path == url_for('main.ticket') %} class="nav-link active"
                        {% else %} class="nav-link"
                        {% endif %} href="{{ url_for('main.ticket') }}"
                    >
                        Ticket
                    </a>
                </li>
                <li class="nav-item">
                    <a {% if request.path == url_for('main.firewall') %} class="nav-link active"
                        {% else %} class="nav-link"
                        {% endif %} href="{{ url_for('main.firewall') }}"
                    >
                        Firewall
                    </a>
                </li>
                <li class="nav-item">
                    <a {% if request.path == url_for('main.access') %} class="nav-link active"
                        {% else %} class="nav-link"
                        {% endif %} href="{{ url_for('main.access') }}"
                    >
                        Access log
                    </a>
                </li>
                <li class="nav-item">
                    <a {% if request.path == url_for('main.error') %} class="nav-link active"
                        {% else %} class="nav-link"
                        {% endif %} href="{{ url_for('main.error') }}"
                    >
                        Error log
                    </a>
                </li>                 
                <li class="nav-item">
                    <a {% if request.path == url_for('main.load') %} class="nav-link active"
                        {% else %} class="nav-link"
                        {% endif %} href="{{ url_for('main.load') }}"
                    >
                        Load chart
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/paging.html
<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if paging.has_prev %}
    <li class="page-item">
        <a class="page-link" href="?page=1">처음</a>
    </li>
    <li class="page-item">
        <a class="page-link" href="?page={{ paging.prev_num }}">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">처음</a>
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %}
    {% for page_num in paging.pages %}
        {% if page_num %}
            {% if page_num != paging.page %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
            </li>
            {% else %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">{{ page_num }}</a>
            </li>
            {% endif %}
        {% else %}
            <li class="disabled">
                <a class="page-link" href="#">...</a>
            </li>
        {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if paging.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ paging.next_num }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
</ul>

templates/table.html
<div class="container-fluid my-3">
    {% if update_title == 'Firewall' %}
    <button type="button" class="btn btn-primary my-3" id="update">
        {{ update_title + ' Update' }}
    </button>
    {% endif %}
    <table class="table">
    {% if data_list %}
        <thead>
            <tr class="table-dark">
                <th class="text-center align-middle">번호</th>
                {% for column in column_header %}
                <th class="text-center align-middle">{{ column.header }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for data in data_list %}
            <tr>
                <td class="text-center align-middle" id="td{{ loop.index0 }}">{{ paging.offset + loop.index0 + 1}}</td>
                {% for column in column_header %}
                {% if column['accessor'] == 'ip'%}
                <td class="text-center align-middle"><a href="{{ analyze_site + data[column['accessor']] }}" target="_blank">{{ data[column['accessor']] }}</a></td>
                {% elif column['accessor'] == 'host' %}
                <td class="text-center align-middle"><a href="{{ url_for('main.access_by_site', site=data[column['accessor']]) }}">{{ data[column['accessor']] }}</a></td>
                {% elif column['accessor'] == 'ticket' %}
                <td class="text-center align-middle"><a href="{{ url_for('main.history', ticket=data[column['accessor']]) }}">{{ data[column['accessor']] }}</a></td>
                {% elif column['accessor'] == 'status' %}
                <td class="text-center align-middle"><a href="{{ url_for('main.access_by_status', status=data[column['accessor']]) }}">{{ data[column['accessor']] }}</a></td>
                {% else %}
                <td class="text-center align-middle">{{ data[column['accessor']] }}</td>
                {% endif %}
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    {% else %}
        <tr>
            <td colspan="3">{{ update_title + ' 정보가 없습니다.' }}</td>
        </tr>
    {% endif %}
    </table>
</div>